require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssemblyGuidesController do

  # This should return the minimal set of attributes required to create a valid
  # AssemblyGuide. As you add validations to AssemblyGuide, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "description" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssemblyGuidesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all assembly_guides as @assembly_guides" do
      assembly_guide = AssemblyGuide.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assembly_guides).should eq([assembly_guide])
    end
  end

  describe "GET show" do
    it "assigns the requested assembly_guide as @assembly_guide" do
      assembly_guide = AssemblyGuide.create! valid_attributes
      get :show, {:id => assembly_guide.to_param}, valid_session
      assigns(:assembly_guide).should eq(assembly_guide)
    end
  end

  describe "GET new" do
    it "assigns a new assembly_guide as @assembly_guide" do
      get :new, {}, valid_session
      assigns(:assembly_guide).should be_a_new(AssemblyGuide)
    end
  end

  describe "GET edit" do
    it "assigns the requested assembly_guide as @assembly_guide" do
      assembly_guide = AssemblyGuide.create! valid_attributes
      get :edit, {:id => assembly_guide.to_param}, valid_session
      assigns(:assembly_guide).should eq(assembly_guide)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssemblyGuide" do
        expect {
          post :create, {:assembly_guide => valid_attributes}, valid_session
        }.to change(AssemblyGuide, :count).by(1)
      end

      it "assigns a newly created assembly_guide as @assembly_guide" do
        post :create, {:assembly_guide => valid_attributes}, valid_session
        assigns(:assembly_guide).should be_a(AssemblyGuide)
        assigns(:assembly_guide).should be_persisted
      end

      it "redirects to the created assembly_guide" do
        post :create, {:assembly_guide => valid_attributes}, valid_session
        response.should redirect_to(AssemblyGuide.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assembly_guide as @assembly_guide" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyGuide.any_instance.stub(:save).and_return(false)
        post :create, {:assembly_guide => { "description" => "invalid value" }}, valid_session
        assigns(:assembly_guide).should be_a_new(AssemblyGuide)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyGuide.any_instance.stub(:save).and_return(false)
        post :create, {:assembly_guide => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assembly_guide" do
        assembly_guide = AssemblyGuide.create! valid_attributes
        # Assuming there are no other assembly_guides in the database, this
        # specifies that the AssemblyGuide created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssemblyGuide.any_instance.should_receive(:update_attributes).with({ "description" => "MyString" })
        put :update, {:id => assembly_guide.to_param, :assembly_guide => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested assembly_guide as @assembly_guide" do
        assembly_guide = AssemblyGuide.create! valid_attributes
        put :update, {:id => assembly_guide.to_param, :assembly_guide => valid_attributes}, valid_session
        assigns(:assembly_guide).should eq(assembly_guide)
      end

      it "redirects to the assembly_guide" do
        assembly_guide = AssemblyGuide.create! valid_attributes
        put :update, {:id => assembly_guide.to_param, :assembly_guide => valid_attributes}, valid_session
        response.should redirect_to(assembly_guide)
      end
    end

    describe "with invalid params" do
      it "assigns the assembly_guide as @assembly_guide" do
        assembly_guide = AssemblyGuide.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyGuide.any_instance.stub(:save).and_return(false)
        put :update, {:id => assembly_guide.to_param, :assembly_guide => { "description" => "invalid value" }}, valid_session
        assigns(:assembly_guide).should eq(assembly_guide)
      end

      it "re-renders the 'edit' template" do
        assembly_guide = AssemblyGuide.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyGuide.any_instance.stub(:save).and_return(false)
        put :update, {:id => assembly_guide.to_param, :assembly_guide => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assembly_guide" do
      assembly_guide = AssemblyGuide.create! valid_attributes
      expect {
        delete :destroy, {:id => assembly_guide.to_param}, valid_session
      }.to change(AssemblyGuide, :count).by(-1)
    end

    it "redirects to the assembly_guides list" do
      assembly_guide = AssemblyGuide.create! valid_attributes
      delete :destroy, {:id => assembly_guide.to_param}, valid_session
      response.should redirect_to(assembly_guides_url)
    end
  end

end
