require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PcbsController do

  # This should return the minimal set of attributes required to create a valid
  # Pcb. As you add validations to Pcb, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PcbsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pcbs as @pcbs" do
      pcb = Pcb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pcbs).should eq([pcb])
    end
  end

  describe "GET show" do
    it "assigns the requested pcb as @pcb" do
      pcb = Pcb.create! valid_attributes
      get :show, {:id => pcb.to_param}, valid_session
      assigns(:pcb).should eq(pcb)
    end
  end

  describe "GET new" do
    it "assigns a new pcb as @pcb" do
      get :new, {}, valid_session
      assigns(:pcb).should be_a_new(Pcb)
    end
  end

  describe "GET edit" do
    it "assigns the requested pcb as @pcb" do
      pcb = Pcb.create! valid_attributes
      get :edit, {:id => pcb.to_param}, valid_session
      assigns(:pcb).should eq(pcb)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pcb" do
        expect {
          post :create, {:pcb => valid_attributes}, valid_session
        }.to change(Pcb, :count).by(1)
      end

      it "assigns a newly created pcb as @pcb" do
        post :create, {:pcb => valid_attributes}, valid_session
        assigns(:pcb).should be_a(Pcb)
        assigns(:pcb).should be_persisted
      end

      it "redirects to the created pcb" do
        post :create, {:pcb => valid_attributes}, valid_session
        response.should redirect_to(Pcb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pcb as @pcb" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pcb.any_instance.stub(:save).and_return(false)
        post :create, {:pcb => { "title" => "invalid value" }}, valid_session
        assigns(:pcb).should be_a_new(Pcb)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pcb.any_instance.stub(:save).and_return(false)
        post :create, {:pcb => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pcb" do
        pcb = Pcb.create! valid_attributes
        # Assuming there are no other pcbs in the database, this
        # specifies that the Pcb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pcb.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => pcb.to_param, :pcb => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested pcb as @pcb" do
        pcb = Pcb.create! valid_attributes
        put :update, {:id => pcb.to_param, :pcb => valid_attributes}, valid_session
        assigns(:pcb).should eq(pcb)
      end

      it "redirects to the pcb" do
        pcb = Pcb.create! valid_attributes
        put :update, {:id => pcb.to_param, :pcb => valid_attributes}, valid_session
        response.should redirect_to(pcb)
      end
    end

    describe "with invalid params" do
      it "assigns the pcb as @pcb" do
        pcb = Pcb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pcb.any_instance.stub(:save).and_return(false)
        put :update, {:id => pcb.to_param, :pcb => { "title" => "invalid value" }}, valid_session
        assigns(:pcb).should eq(pcb)
      end

      it "re-renders the 'edit' template" do
        pcb = Pcb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pcb.any_instance.stub(:save).and_return(false)
        put :update, {:id => pcb.to_param, :pcb => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pcb" do
      pcb = Pcb.create! valid_attributes
      expect {
        delete :destroy, {:id => pcb.to_param}, valid_session
      }.to change(Pcb, :count).by(-1)
    end

    it "redirects to the pcbs list" do
      pcb = Pcb.create! valid_attributes
      delete :destroy, {:id => pcb.to_param}, valid_session
      response.should redirect_to(pcbs_url)
    end
  end

end
