require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SupplierSkusController do

  # This should return the minimal set of attributes required to create a valid
  # SupplierSku. As you add validations to SupplierSku, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "sku" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupplierSkusController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all supplier_skus as @supplier_skus" do
      supplier_sku = SupplierSku.create! valid_attributes
      get :index, {}, valid_session
      assigns(:supplier_skus).should eq([supplier_sku])
    end
  end

  describe "GET show" do
    it "assigns the requested supplier_sku as @supplier_sku" do
      supplier_sku = SupplierSku.create! valid_attributes
      get :show, {:id => supplier_sku.to_param}, valid_session
      assigns(:supplier_sku).should eq(supplier_sku)
    end
  end

  describe "GET new" do
    it "assigns a new supplier_sku as @supplier_sku" do
      get :new, {}, valid_session
      assigns(:supplier_sku).should be_a_new(SupplierSku)
    end
  end

  describe "GET edit" do
    it "assigns the requested supplier_sku as @supplier_sku" do
      supplier_sku = SupplierSku.create! valid_attributes
      get :edit, {:id => supplier_sku.to_param}, valid_session
      assigns(:supplier_sku).should eq(supplier_sku)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SupplierSku" do
        expect {
          post :create, {:supplier_sku => valid_attributes}, valid_session
        }.to change(SupplierSku, :count).by(1)
      end

      it "assigns a newly created supplier_sku as @supplier_sku" do
        post :create, {:supplier_sku => valid_attributes}, valid_session
        assigns(:supplier_sku).should be_a(SupplierSku)
        assigns(:supplier_sku).should be_persisted
      end

      it "redirects to the created supplier_sku" do
        post :create, {:supplier_sku => valid_attributes}, valid_session
        response.should redirect_to(SupplierSku.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supplier_sku as @supplier_sku" do
        # Trigger the behavior that occurs when invalid params are submitted
        SupplierSku.any_instance.stub(:save).and_return(false)
        post :create, {:supplier_sku => { "sku" => "invalid value" }}, valid_session
        assigns(:supplier_sku).should be_a_new(SupplierSku)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SupplierSku.any_instance.stub(:save).and_return(false)
        post :create, {:supplier_sku => { "sku" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supplier_sku" do
        supplier_sku = SupplierSku.create! valid_attributes
        # Assuming there are no other supplier_skus in the database, this
        # specifies that the SupplierSku created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SupplierSku.any_instance.should_receive(:update_attributes).with({ "sku" => "MyString" })
        put :update, {:id => supplier_sku.to_param, :supplier_sku => { "sku" => "MyString" }}, valid_session
      end

      it "assigns the requested supplier_sku as @supplier_sku" do
        supplier_sku = SupplierSku.create! valid_attributes
        put :update, {:id => supplier_sku.to_param, :supplier_sku => valid_attributes}, valid_session
        assigns(:supplier_sku).should eq(supplier_sku)
      end

      it "redirects to the supplier_sku" do
        supplier_sku = SupplierSku.create! valid_attributes
        put :update, {:id => supplier_sku.to_param, :supplier_sku => valid_attributes}, valid_session
        response.should redirect_to(supplier_sku)
      end
    end

    describe "with invalid params" do
      it "assigns the supplier_sku as @supplier_sku" do
        supplier_sku = SupplierSku.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SupplierSku.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplier_sku.to_param, :supplier_sku => { "sku" => "invalid value" }}, valid_session
        assigns(:supplier_sku).should eq(supplier_sku)
      end

      it "re-renders the 'edit' template" do
        supplier_sku = SupplierSku.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SupplierSku.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplier_sku.to_param, :supplier_sku => { "sku" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supplier_sku" do
      supplier_sku = SupplierSku.create! valid_attributes
      expect {
        delete :destroy, {:id => supplier_sku.to_param}, valid_session
      }.to change(SupplierSku, :count).by(-1)
    end

    it "redirects to the supplier_skus list" do
      supplier_sku = SupplierSku.create! valid_attributes
      delete :destroy, {:id => supplier_sku.to_param}, valid_session
      response.should redirect_to(supplier_skus_url)
    end
  end

end
